export class Ctap2ClientPinVersionUnsupported extends Error { }
export class Ctap2PingDataMissmatch extends Error { }
export class Ctap2TransportUnsupported extends Error { }
export class Ctap2InvalidCommand extends Error { }
export class Ctap2InvalidStatus extends Error { }
export class Ctap1ErrSuccess extends Error { }
export class Ctap2Ok extends Error { }
export class Ctap1ErrInvalidCommand extends Error { }
export class Ctap1ErrInvalidParameter extends Error { }
export class Ctap1ErrInvalidLength extends Error { }
export class Ctap1ErrInvalidSeq extends Error { }
export class Ctap1ErrTimeout extends Error { }
export class Ctap1ErrChannelBusy extends Error { }
export class Ctap1ErrLockRequired extends Error { }
export class Ctap1ErrInvalidChannel extends Error { }
export class Ctap2ErrCborUnexpectedType extends Error { }
export class Ctap2ErrInvalidCbor extends Error { }
export class Ctap2ErrMissingParameter extends Error { }
export class Ctap2ErrLimitExceeded extends Error { }
export class Ctap2ErrFpDatabaseFull extends Error { }
export class Ctap2ErrLargeBlobStorageFull extends Error { }
export class Ctap2ErrCredentialExcluded extends Error { }
export class Ctap2ErrProcessing extends Error { }
export class Ctap2ErrInvalidCredential extends Error { }
export class Ctap2ErrUserActionPending extends Error { }
export class Ctap2ErrOperationPending extends Error { }
export class Ctap2ErrNoOperations extends Error { }
export class Ctap2ErrUnsupportedAlgorithm extends Error { }
export class Ctap2ErrOperationDenied extends Error { }
export class Ctap2ErrKeyStoreFull extends Error { }
export class Ctap2ErrUnsupportedOption extends Error { }
export class Ctap2ErrInvalidOption extends Error { }
export class Ctap2ErrKeepaliveCancel extends Error { }
export class Ctap2ErrNoCredentials extends Error { }
export class Ctap2ErrUserActionTimeout extends Error { }
export class Ctap2ErrNotAllowed extends Error { }
export class Ctap2ErrPinInvalid extends Error { }
export class Ctap2ErrPinBlocked extends Error { }
export class Ctap2ErrPinAuthInvalid extends Error { }
export class Ctap2ErrPinAuthBlocked extends Error { }
export class Ctap2ErrPinNotSet extends Error { }
export class Ctap2ErrPuatRequired extends Error { }
export class Ctap2ErrPinPolicyViolation extends Error { }
export class Ctap2ErrReserved extends Error { }
export class Ctap2ErrRequestTooLarge extends Error { }
export class Ctap2ErrActionTimeout extends Error { }
export class Ctap2ErrUpRequired extends Error { }
export class Ctap2ErrUvBlocked extends Error { }
export class Ctap2ErrIntegrityFailure extends Error { }
export class Ctap2ErrInvalidSubcommand extends Error { }
export class Ctap2ErrUvInvalid extends Error { }
export class Ctap2ErrUnauthorizedPermission extends Error { }
export class Ctap1ErrOther extends Error { }
export class Ctap2ErrSpecLast extends Error { }
export class Ctap2ErrExtensionFirst extends Error { }
export class Ctap2ErrExtensionLast extends Error { }
export class Ctap2ErrVendorFirst extends Error { }
export class Ctap2ErrVendorLast extends Error { }