/**
 *
 * @type {{GET_INFO: number, CLIENT_PIN: number, CREDENTIAL_MGMT: number, MAKE_CREDENTIAL: number, GET_NEXT_ASSERTION: number, RESET: number, GET_ASSERTION: number}}
 */
module.exports.CTAP2_CMD = {
    MAKE_CREDENTIAL: 0x01,
    GET_ASSERTION: 0x02,
    GET_INFO: 0x04,
    CLIENT_PIN: 0x06,
    RESET: 0x07,
    GET_NEXT_ASSERTION: 0x08,
    CREDENTIAL_MGMT: 0x41
};

/**
 *
 * @type {{MAX_CREDS_IN_LIST: number, EXTENSIONS: number, MAX_MSG_SIZE: number, VERSION: number, AAGUID: number, PIN_PROTOCOLS: number, MAX_CRED_ID_LENGTH: number, ALGORITHMS: number, OPTIONS: number, TRANSPORTS: number}}
 */
module.exports.GET_INFO_CBOR = {
    VERSION: 0x01,
    EXTENSIONS: 0x02,
    AAGUID: 0x03,
    OPTIONS: 0x04,
    MAX_MSG_SIZE: 0x05,
    PIN_PROTOCOLS: 0x06,
    MAX_CREDS_IN_LIST: 0x07,
    MAX_CRED_ID_LENGTH: 0x08,
    TRANSPORTS: 0x09,
    ALGORITHMS: 0x0A,
};

/**
 *
 * @type {{PIN_TOKEN: number, KEY_AGREEMENT: number, RETRIES: number, POWER_CYCLE_STATE: number}}
 */
module.exports.CLIENT_PIN_CBOR = {
    KEY_AGREEMENT: 0x01,
    PIN_TOKEN: 0x02,
    RETRIES: 0x03,
    POWER_CYCLE_STATE: 0x4
};

/**
 *
 * @type {{CBOR: {PIN_TOKEN: number, KEY_AGREEMENT: number, RETRIES: number}}}
 */
module.exports.CLIENT_PIN = {
    CBOR: {
        KEY_AGREEMENT: 0x01,
        PIN_TOKEN: 0x02,
        RETRIES: 0x03
    }
};

/**
 *
 * @type {{USER_VERIFIED: number, ATTESTED: number, USER_PRESENT: number, EXTENSION_DATA: number}}
 */
module.exports.AUTH_DATA_FLAGS = {
    USER_PRESENT: 0x01,
    USER_VERIFIED: 0x04,
    ATTESTED: 0x40,
    EXTENSION_DATA: 0x80,
};

/**
 *
 * @type {{AUTH_DATA: number, ATT_STMT: number, FMT: number}}
 */
module.exports.ATTESTATION_CBOR = {
    FMT: 1,
    AUTH_DATA: 2,
    ATT_STMT: 3,
};

/**
 *
 * @type {{AUTH_DATA: number, CREDENTIAL: number, USER: number, N_CREDS: number, SIGNATURE: number}}
 */
module.exports.ASSERTION_CBOR = {
    CREDENTIAL: 1,
    AUTH_DATA: 2,
    SIGNATURE: 3,
    USER: 4,
    N_CREDS: 5,
};

/**
 *
 * @type {{GET_KEY_AGREEMENT: number, GET_PIN_TOKEN: number, SET_PIN: number, GET_RETRIES: number, CHANGE_PIN: number}}
 */
module.exports.CLIENT_PIN_CMD = {
    GET_RETRIES: 0x01,
    GET_KEY_AGREEMENT: 0x02,
    SET_PIN: 0x03,
    CHANGE_PIN: 0x04,
    GET_PIN_TOKEN: 0x05
};

/**
 *
 * @type {{INVALID_SEQ: number, LOCK_REQUIRED: number, CBOR_UNEXPECTED_TYPE: number, INVALID_OPTION: number, PROCESSING: number, KEY_STORE_FULL: number, PIN_TOKEN_EXPIRED: number, INVALID_COMMAND: number, UNSUPPORTED_OPTION: number, VENDOR_LAST: number, CREDENTIAL_EXCLUDED: number, EXTENSION_FIRST: number, CHANNEL_BUSY: number, UNSUPPORTED_EXTENSION: number, ACTION_TIMEOUT: number, PIN_POLICY_VIOLATION: number, SPEC_LAST: number, INVALID_LENGTH: number, INVALID_CHANNEL: number, PIN_BLOCKED: number, LIMIT_EXCEEDED: number, OPERATION_PENDING: number, USER_ACTION_TIMEOUT: number, OPERATION_DENIED: number, NOT_BUSY: number, PIN_REQUIRED: number, SUCCESS: number, PIN_INVALID: number, KEEPALIVE_CANCEL: number, NO_CREDENTIALS: number, REQUEST_TOO_LARGE: number, NOT_ALLOWED: number, NO_OPERATION_PENDING: number, INVALID_PARAMETER: number, INVALID_CBOR: number, NO_OPERATIONS: number, PIN_AUTH_INVALID: number, VENDOR_FIRST: number, MISSING_PARAMETER: number, PIN_AUTH_BLOCKED: number, OTHER: number, USER_ACTION_PENDING: number, TIMEOUT: number, UP_REQUIRED: number, EXTENSION_LAST: number, INVALID_CREDENTIAL: number, UNSUPPORTED_ALGORITHM: number, PIN_NOT_SET: number}}
 */
module.exports.ERRORS = {
    SUCCESS: 0x00,
    INVALID_COMMAND: 0x01,
    INVALID_PARAMETER: 0x02,
    INVALID_LENGTH: 0x03,
    INVALID_SEQ: 0x04,
    TIMEOUT: 0x05,
    CHANNEL_BUSY: 0x06,
    LOCK_REQUIRED: 0x0A,
    INVALID_CHANNEL: 0x0B,
    CBOR_UNEXPECTED_TYPE: 0x11,
    INVALID_CBOR: 0x12,
    MISSING_PARAMETER: 0x14,
    LIMIT_EXCEEDED: 0x15,
    UNSUPPORTED_EXTENSION: 0x16,
    CREDENTIAL_EXCLUDED: 0x19,
    PROCESSING: 0x21,
    INVALID_CREDENTIAL: 0x22,
    USER_ACTION_PENDING: 0x23,
    OPERATION_PENDING: 0x24,
    NO_OPERATIONS: 0x25,
    UNSUPPORTED_ALGORITHM: 0x26,
    OPERATION_DENIED: 0x27,
    KEY_STORE_FULL: 0x28,
    NOT_BUSY: 0x29,
    NO_OPERATION_PENDING: 0x2A,
    UNSUPPORTED_OPTION: 0x2B,
    INVALID_OPTION: 0x2C,
    KEEPALIVE_CANCEL: 0x2D,
    NO_CREDENTIALS: 0x2E,
    USER_ACTION_TIMEOUT: 0x2F,
    NOT_ALLOWED: 0x30,
    PIN_INVALID: 0x31,
    PIN_BLOCKED: 0x32,
    PIN_AUTH_INVALID: 0x33,
    PIN_AUTH_BLOCKED: 0x34,
    PIN_NOT_SET: 0x35,
    PIN_REQUIRED: 0x36,
    PIN_POLICY_VIOLATION: 0x37,
    PIN_TOKEN_EXPIRED: 0x38,
    REQUEST_TOO_LARGE: 0x39,
    ACTION_TIMEOUT: 0x3A,
    UP_REQUIRED: 0x3B,
    OTHER: 0x7F,
    SPEC_LAST: 0xDF,
    EXTENSION_FIRST: 0xE0,
    EXTENSION_LAST: 0xEF,
    VENDOR_FIRST: 0xF0,
    VENDOR_LAST: 0xFF,
};

/**
 *
 * @type {{PROCESSING: number, UNNEEDED: number}}
 */
module.exports.KEEPALIVE_STATUS = {
    PROCESSING: 1,
    UNNEEDED: 2
};

/**
 *
 * @type {number}
 */
module.exports.PIN_PROTOCOL_VERSION = 1;